### PR TITLE
Update pantheon cli version

### PR DESCRIPTION
**Pull request by devkinetic**
Need this to support machine tokens.

### CODE REVIEW

**Comment by dixhuit** [comment]
`pantheon_cli_version` is a default variable and as such can be overridden with any value you like from the Ansible playbook that is using this role.

**Comment by devkinetic** [comment]
The main reason I suggested this update to the source is that terminus has moved away from user/pass and instead requires machine keys.  This makes it somewhat of a security update. Also, the role in vlad that currently requires this role does not function in it's current state. 

I'm not as well versed in playbooks and the like but with what your saying, the pantheon_import role in vlad should extend the value of the cli version instead? Or possibly the Vagrantfile? My main goal was to get pantheon working out of the box for vlad.

**Comment by dixhuit** [comment]
In that case you should just be able to add the following to your vlad_settings.yml file:

```
pantheon_cli_version: 0.11.4
```

If that doesn't work then this is an issue for Vlad rather than this particular role. Granted they're related but all roles abstracted away from Vlad are supposed to not assume that they'll be used in Vlad.

Keep me posted! :)

**Comment by devkinetic** [comment]
I'll try a barebones vlad pantheon import using only the cli bump and see if that works.

**Comment by dixhuit** [comment]
@devkinetic You'll (hopefully) be pleased to know that I just bumped the default Pantheon CLI version to 0.13.1.

**Pull request closed without merging**
